### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by WindowsMeosu** [WindowsMeosu/hexchat#3]
- [ ] create compilation workflows for other Linux distributions, such as Fedora
- [ ] rework the Windows compilation workflow to allow compilation for ARM64
- [ ] implement IRCv3 specifications that hadn't been incorporated into HexChat; if possible
